BASE_TASK_CONFIG_PATH: VLN_CE/habitat_extensions/config/vlnce_task_aux_think_r2r_train.yaml
EVAL:
    IDENTIFICATION: r2r
    SPLIT: val_unseen
    # any num greater than the actual episode count evals every episode
    EARLY_STOP_ROTATION: 25
    EARLY_STOP_STEPS: 400



